# More on NumPy

We have used NumPy already, but there is more that you can do with it, and much of its function is useful in physics modeling. NumPy provides fast, _vectorized_ numerical computations using arrays.

## Review

**Evaluate the following cells**

In [2]:
import numpy as np
np.__version__

'2.0.2'

In [3]:
# explore NumPy
dir(np)[:20] # first 20 entries

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__']

In [4]:
# get help for a specific function
help(np.sin)

Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [5]:
# COMPLETE THIS TASK
# Find documentation for np.linspace using '?'
np.linspace?

## Creating Vectors and Matrices

### Creating vectors

In [7]:
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3

(array([1, 2, 3]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0, 2, 4, 6, 8]))

### Creating matrices

In [8]:
A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I

(array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

### Indexing and slicing

In [9]:
A[0, 1], A[:, 0], A[1]

(np.int64(2), array([1, 3]), array([3, 4]))

### Random matrices

In [10]:
R = np.random.randn(3,3)
U = np.random.rand(3,3)
R, U

(array([[ 0.9740911 ,  1.65545504,  1.11582094],
        [ 0.76012423,  0.37041115,  0.49097895],
        [-0.70805616,  2.03559369,  0.51442899]]),
 array([[4.62046854e-04, 1.35440929e-01, 2.93379444e-01],
        [8.90960836e-01, 1.35414547e-01, 7.19635782e-01],
        [4.14151318e-01, 7.71141754e-01, 6.80609096e-01]]))

In [19]:
# COMPLETE THIS TASK
# Decompose a 5×5 random matrix into (real) symmetric and antisymmetric parts.
# A symmetric matrix A satisfies A = 0.5*(A + A.T);
# An antisymmetric matrix satisfies A = 0.5*(A - A.T);
# The `.T` attribute finds the transpose of the matrix.
S = np.random.randn(5,5)
A = 0.5*(S + S.T)
B = 0.5*(S - S.T)
A, B


(array([[-0.10669554,  1.57064649, -0.26169237,  0.30214697, -0.37489234],
        [ 1.57064649,  1.30190173,  0.00652163, -0.35558197, -0.58403028],
        [-0.26169237,  0.00652163, -0.24213219, -0.35248758, -0.5146781 ],
        [ 0.30214697, -0.35558197, -0.35248758, -1.92316467,  0.04127429],
        [-0.37489234, -0.58403028, -0.5146781 ,  0.04127429,  1.03956038]]),
 array([[ 0.        , -0.97045139, -0.59643048,  1.08217177,  0.91421943],
        [ 0.97045139,  0.        , -0.6973786 , -0.1395397 , -0.43999867],
        [ 0.59643048,  0.6973786 ,  0.        , -0.52512688,  0.18433523],
        [-1.08217177,  0.1395397 ,  0.52512688,  0.        ,  0.29471271],
        [-0.91421943,  0.43999867, -0.18433523, -0.29471271,  0.        ]]))

## Operations: *, @, and np.matmul / np.dot

Elementwise and matrix multiplication are treated differently in Numpy.

### Elementwise multiplication (`*`)

In [12]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

array([[ 10,  40],
       [ 90, 160]])

### Matrix multiplication (`@`)

In [13]:
A @ B

array([[ 70, 100],
       [150, 220]])

### Function equivalents for matrix multiplication

In [14]:
np.matmul(A, B), np.dot(A, B)

(array([[ 70, 100],
        [150, 220]]),
 array([[ 70, 100],
        [150, 220]]))

In [25]:
# COMPLETE THESE TASKS
# 1. look into the documentation for `np.matmul`, `np.dot`, `@`, and `*` and explain their difference(s)
# 2. create an example/examples to explain their differences

# np.matmul? # matrix product of two arrays
# np.dot? # dot product of two arrays
# documentation for `@`: https://peps.python.org/pep-0465/
# documentation for `*`: "Currently, most numerical Python code uses * for elementwise multiplication, and function/method syntax for matrix multiplication; however, this leads to ugly and unreadable code in common circumstances"

# 2D example
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
np.matmul(A, B), np.dot(A, B), A@B, A*B

# `*` performs element-wise multiplication, which is why the result is different.
# `@` is the dedicated operator for matrix multiplication
# np.matmul() behaves similarly to `@` and handles higher-dimensional arrays that aligns with matrix products
# np.dot() is general and performs a dot product; different behavior for 1D arrays and higher-dimensional arrays

# higher-dimensional array example
E = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
F = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
np.matmul(E, F), np.dot(E, F), E@F, E*F



(array([[[  70,  100],
         [ 150,  220]],
 
        [[ 670,  780],
         [ 910, 1060]]]),
 array([[[[  70,  100],
          [ 190,  220]],
 
         [[ 150,  220],
          [ 430,  500]]],
 
 
        [[[ 230,  340],
          [ 670,  780]],
 
         [[ 310,  460],
          [ 910, 1060]]]]),
 array([[[  70,  100],
         [ 150,  220]],
 
        [[ 670,  780],
         [ 910, 1060]]]),
 array([[[ 10,  40],
         [ 90, 160]],
 
        [[250, 360],
         [490, 640]]]))

## Vectorization and Performance

_Vectorization_ means applying operations to whole arrays at once, rather than element by element.

### Loop version -- one element at a time

In [26]:
import math

In [29]:
%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
ys_loop = np.zeros_like(xs)
for i in range(len(xs)):
  ys_loop[i] = math.sin(xs[i])

279 ms ± 7.23 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Vectorized version

In [30]:
%%timeit
import numpy as np
xs = np.linspace(0, 10, 1_000_000)
y_vec = np.sin(xs)

20.9 ms ± 3.93 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# COMPLETE THIS TASK
# ask Gemini about `%%timeit`
# Here's what Gemini had to say:
# The %%timeit is a Jupyter/IPython magic command that times the execution of a Python statement or expression. It runs the code multiple times and provides the mean and standard deviation of the execution times.

# Here's how it generally works:

#Execution in a loop: It executes the code snippet many times (usually a default number of loops and runs) to get a statistically reliable measurement.
# Warm-up runs: It performs some warm-up runs to ensure that any initial overhead (like module imports or JIT compilation) doesn't skew the results.
# Best of N runs: It typically reports the best time out of a certain number of runs to minimize the impact of system noise (other processes running, caching, etc.).
#Mean and standard deviation: The output you saw, like 279 ms ± 7.23 ms per loop, indicates the average time per loop and the variability across different runs.
# It's very useful for comparing the performance of different implementations of the same task, especially when trying to optimize code, as you observed when comparing the loop version to the vectorized NumPy version.

In [ ]:
# COMPLETE THIS TASK
# create a vectorized function that calculates the total energy (T+U; kinetic + potential energy) of a harmonic oscillator
def total_harmonic_oscillator_energy(x, v, m, k):
    """
    Calculates the total energy (Kinetic + Potential) of a harmonic oscillator in a vectorized manner.

    Parameters:
    x (np.ndarray): Array of positions.
    v (np.ndarray): Array of velocities.
    m (float): Mass of the oscillator.
    k (float): Spring constant.

    Returns:
    np.ndarray: Array of total energies.
    """
    kinetic_energy = 0.5 * m * v**2
    potential_energy = 0.5 * k * x**2
    total_energy = kinetic_energy + potential_energy
    return total_energy

# Example usage:
mass = 1.0
k_spring = 10.0

# Create arrays for position and velocity
positions = np.array([0.1, 0.5, -0.2])
velocities = np.array([0.0, 0.3, 0.1])

energies = total_harmonic_oscillator_energy(positions, velocities, mass, k_spring)
print("Positions:", positions)
print("Velocities:", velocities)
print("Total Energies:", energies)

## Eigenvalues and Eigenvectors

For a matrix $M$, eigenvalues $\lambda$ and eigenvectors $v$ satisfy:
$$ M v = \lambda v $$

In physics, these often realte to characteristic and measurable physical quantities:
* Oscillators → $\lambda$ relates to squared frequencies
* Quantum mechanics → $\lambda$ could be the energy eigenstates
* Rotations → $\lambda$ could define a principal axes

### Here is an example matrix

In [31]:
K = np.array([[ 1,-1, 0]
             ,[-1, 2,-1]
             ,[ 0,-1, 1] ])
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([9.99658224e-17, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
        [-5.77350269e-01,  9.71445147e-17, -8.16496581e-01],
        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

In [ ]:
# COMPLETE THIS TASK
# In the above cell, which eigenvector is associated with which eigenvalue?
# The first eigenvalue corresponds to the first eigenvector, and so on.

## Quadratic Form: Diatomic Molecule Model

We can model a diatomic molecule (O$_2$ or N$_2$, for example) as two masses connected by a spring. Motion is restricted to the
bond axis.

The (quadratic) potential energy is: `V = 0.5 * x.T @ K @ x ` where `x = (x1, x2)`, the coordinates of the two atoms.

### Constructing a stiffness/force-constant matrix

In [32]:
k = 2450 # the force constant in an appropriate [energy]/[length] units
K = np.array([[ k,-k]
             ,[-k, k]])
K

array([[ 2450, -2450],
       [-2450,  2450]])

### Diagonalize to find frequencies and normal mode displacement patterns

In [33]:
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([   0., 4900.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

### Vibrational frequencies (ignoring mass)

In [34]:
omega = np.sqrt(vals)
omega

array([ 0., 70.])

### Unitary transformations with eigenvector matrices

If the matrix is not singular, we can find eigenvalues and eigenvectors. The matrix of eigenvectors $U$ forms a unitary transformation.

In [35]:
# COMPLETE THESE TASKS
# Show that U@U.T and U.T@U are 2x2 identity matrices
# Note that normally we would need to use the `.conj().T` attribute to find the conjugate transpose matric, but our matrix is real.
U = np.array([[ 0.70710678, -0.70710678]
             ,[ 0.70710678,  0.70710678]])
U@U.T, U.T@U

(array([[ 9.99999997e-01, -1.18727821e-17],
        [-1.18727821e-17,  9.99999997e-01]]),
 array([[9.99999997e-01, 1.18727821e-17],
        [1.18727821e-17, 9.99999997e-01]]))

In [37]:
# COMPLETE THIS TASK
# From the eigenvalue equation M v = λ v, it follows that for U = [v1, v2], then M U = λ U.
# Because λ is diagonal and U.T@U = np.eye(2), it follows that λ = U.T @ K @ U.
# Confirm this behavior.
U.T@U, np.eye(2), U.T @ K @ U

# example:

# 1. Define the matrix K
K = np.array([[ 1, -1,  0],
              [-1,  2, -1],
              [ 0, -1,  1]])

# 2. Calculate the eigenvalues (vals) and eigenvectors (U)
vals, U = np.linalg.eigh(K)

# 3. Select the first eigenvector (v1) and eigenvalue (lambda1)
# The first column of U is v1, and the first element of vals is lambda1.
lambda1 = vals[0]
v1 = U[:, 0]

# 4. Calculate K * v1 (Left-Hand Side of the equation)
K_v1 = K @ v1

# 5. Calculate lambda1 * v1 (Right-Hand Side of the equation)
lambda1_v1 = lambda1 * v1

# Print the results
print(f"Eigenvalue 1 (lambda1): {lambda1}")
print(f"Eigenvector 1 (v1):\n{v1}")
print("-" * 50)
print(f"Result of K @ v1 (Left-Hand Side):\n{K_v1}")
print(f"Result of lambda1 * v1 (Right-Hand Side):\n{lambda1_v1}")
print("-" * 50)

# 6. Compare the results
is_close = np.allclose(K_v1, lambda1_v1)
print(f"Are K @ v1 and lambda1 * v1 numerically close? {is_close}")
print(f"Difference (K @ v1 - lambda1 * v1):\n{K_v1 - lambda1_v1}")

Eigenvalue 1 (lambda1): 9.996582244115599e-17
Eigenvector 1 (v1):
[-0.57735027 -0.57735027 -0.57735027]
--------------------------------------------------
Result of K @ v1 (Left-Hand Side):
[ 0.00000000e+00  1.11022302e-16 -1.11022302e-16]
Result of lambda1 * v1 (Right-Hand Side):
[-5.77152945e-17 -5.77152945e-17 -5.77152945e-17]
--------------------------------------------------
Are K @ v1 and lambda1 * v1 numerically close? True
Difference (K @ v1 - lambda1 * v1):
[ 5.77152945e-17  1.68737597e-16 -5.33070080e-17]


In [38]:
# COMPLETE THIS TASK
# Use the eigenvectors to eigenvalues to interpret the two modes in this model of a diatomic molecule
import numpy as np

# 1. Define the matrix K (from the previous context: linear triatomic chain)
K = np.array([[ 1, -1,  0],
              [-1,  2, -1],
              [ 0, -1,  1]])

# 2. Calculate the eigenvalues (vals) and eigenvectors (U)
vals, U = np.linalg.eigh(K)

# 3. Interpret and print the modes

# The eigenvectors are the columns of U.
v1 = U[:, 0]
v2 = U[:, 1]
v3 = U[:, 2]

print("## Normal Modes of Vibration (Triatomic Chain)")
print(f"Matrix K:\n{K}")
print("-" * 50)
print(f"Eigenvalues (Squared Frequencies, vals):\n{vals}")
print("-" * 50)

# Mode 0 (Rigid-Body)
print("### 1. Mode 0: Rigid-Body Translation (λ ≈ 0)")
print(f"Eigenvalue (λ): {vals[0]:.2e}")
print(f"Eigenvector (v1):\n{v1}")
# To show the proportional relationship (1, 1, 1) - use a loop or list comprehension for formatting
v1_scaled = v1 / v1[0]
print(f"Mode Shape (Proportional): [{', '.join(f'{x:.2f}' for x in v1_scaled)}] (All masses move together)")
print("-" * 50)

# Mode 1 (Low Frequency)
print("### 2. Mode 1: Low-Frequency Oscillation (λ = 1.0)")
print(f"Eigenvalue (λ): {vals[1]:.2f}")
print(f"Eigenvector (v2):\n{v2}")
# To show the proportional relationship (-1, 0, 1)
scale_factor = v2[0]
v2_scaled = v2 / scale_factor
print(f"Mode Shape (Proportional): [{', '.join(f'{x:.2f}' for x in v2_scaled)}] (Outer masses move opposite, middle is stationary)")
print("-" * 50)

# Mode 2 (High Frequency)
print("### 3. Mode 2: High-Frequency Oscillation (λ = 3.0)")
print(f"Eigenvalue (λ): {vals[2]:.2f}")
print(f"Eigenvector (v3):\n{v3}")
# To show the proportional relationship (1, -2, 1)
scale_factor = v3[0]
v3_scaled = v3 / scale_factor
print(f"Mode Shape (Proportional): [{', '.join(f'{x:.2f}' for x in v3_scaled)}] (Outer masses move same way, middle moves opposite and twice as much)")

## Normal Modes of Vibration (Triatomic Chain)
Matrix K:
[[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  1]]
--------------------------------------------------
Eigenvalues (Squared Frequencies, vals):
[9.99658224e-17 1.00000000e+00 3.00000000e+00]
--------------------------------------------------
### 1. Mode 0: Rigid-Body Translation (λ ≈ 0)
Eigenvalue (λ): 1.00e-16
Eigenvector (v1):
[-0.57735027 -0.57735027 -0.57735027]
Mode Shape (Proportional): [1.00, 1.00, 1.00] (All masses move together)
--------------------------------------------------
### 2. Mode 1: Low-Frequency Oscillation (λ = 1.0)
Eigenvalue (λ): 1.00
Eigenvector (v2):
[-7.07106781e-01  9.71445147e-17  7.07106781e-01]
Mode Shape (Proportional): [1.00, -0.00, -1.00] (Outer masses move opposite, middle is stationary)
--------------------------------------------------
### 3. Mode 2: High-Frequency Oscillation (λ = 3.0)
Eigenvalue (λ): 3.00
Eigenvector (v3):
[ 0.40824829 -0.81649658  0.40824829]
Mode Shape (Proportional): [1.00, -2.00, 1.00]